#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x93C08C88471097CD (marcel.schaible@studium.fernuni-hagen.de)
#
Name     : gperf
Version  : 3.1
Release  : 18
URL      : https://mirrors.kernel.org/gnu/gperf/gperf-3.1.tar.gz
Source0  : https://mirrors.kernel.org/gnu/gperf/gperf-3.1.tar.gz
Source99 : https://mirrors.kernel.org/gnu/gperf/gperf-3.1.tar.gz.sig
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0 GPL-3.0+
Requires: gperf-bin
Requires: gperf-doc

%description
This is GNU gperf. It is a program that generates perfect hash
functions for sets of key words.  A perfect hash function is:

%package bin
Summary: bin components for the gperf package.
Group: Binaries

%description bin
bin components for the gperf package.


%package doc
Summary: doc components for the gperf package.
Group: Documentation

%description doc
doc components for the gperf package.


%prep
%setup -q -n gperf-3.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1520913036
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make check all ||:

%install
export SOURCE_DATE_EPOCH=1520913036
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/gperf

%files doc
%defattr(-,root,root,-)
%doc /usr/share/info/*
%doc /usr/share/man/man1/*
/usr/share/doc/gperf.html
